name: $(BuildID)
jobs:
  - job: Restart_Jmeter_Slaves
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      cluster_name: jubernetes
      cluster_resource_group: jmeter-group
      cluster_namespace: jubernetes2
      cluster_url: https://jubernetes-dns-782297cf.hcp.westeurope.azmk8s.io:443 #get it from kubectl cluster-info
    timeoutInMinutes: 5

    steps:
      - script: |
          echo $(System.AccessToken) | az login
          az aks get-credentials --resource-group $(cluster_resource_group) --name $(cluster_name)
        displayName: 'Get Kubernetes Credentials'

      - script: az extension add -n azure-devops
        displayName: 'Install Azure DevOps Extension'


      - script: |
          echo $(System.AccessToken) | az devops login
          az devops configure --defaults organization=https://dev.azure.com/gstarczewski project="jmeter" --use-git-aliases true
        displayName: 'Login and Set default Azure DevOps organization and project'

      - script: |
          echo $(System.AccessToken) | az devops login
          kubectl config set-cluster $(cluster_name) --server=$(cluster_url)
          kubectl config use-context $(cluster_name)
          echo "Current state"
          kubectl get pods -n $(cluster_namespace)
          kubectl scale deployment jmeter-slaves --replicas=0 -n $(cluster_namespace)
        displayName: 'Scale to 0'

      - script: |
          echo "Rescaling cluster"
          kubectl get pods -n jubernetes2

        displayName: 'Dispay status'

