#This pipeline is configured with PAT so requires TFA - need to be refactored so it is not required
#restarting is done by scaling to 0 and back to desired number of slaves = all pods - 1
name: $(BuildID)
jobs:
  - job: Restart_Jmeter_Slaves
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      cluster_name: jubernetes
      cluster_resource_group: jmeter-group
      cluster_namespace: jubernetes2
      cluster_url: https://jubernetes-dns-782297cf.hcp.westeurope.azmk8s.io:443 #get it from kubectl cluster-info
      scale_down_replicas: 0
      scale_up_replicas: 2

    timeoutInMinutes: 5

    steps:
      - script: |
          echo $(System.AccessToken) | az login
          az aks get-credentials --resource-group $(cluster_resource_group) --name $(cluster_name)
        displayName: 'Get Kubernetes Credentials'

      - script: |
          kubectl get pods -n $(cluster_namespace)
          kubectl scale deployment jmeter-slaves --replicas=$(scale_up_replicas) -n $(cluster_namespace)
        displayName: 'Scale up'

      - script: |
          echo "Rescaling cluster"
          kubectl get pods -n $(cluster_namespace)
        displayName: 'Display status'

      - task: ShellScript@2
        inputs:
          scriptPath: $(System.DefaultWorkingDirectory)/start_test_from_script.sh $(cluster_namespace)
        displayName: 'Run dummy test'