#This pipeline is configured with PAT so requires TFA - need to be refactored so it is not required
#restarting is done by scaling to 0 and back to desired number of slaves = all pods - 1
name: $(BuildID)
jobs:
  - job: Restart_Jmeter_Slaves
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      azure_subscription_endpoint: p
      azure_resource_group: jmeter-group
      cluster_name: jubernetes
      cluster_resource_group: jmeter-group
      cluster_namespace: jubernetes2

      cluster_url: https://jubernetes-dns-782297cf.hcp.westeurope.azmk8s.io:443 #get it from kubectl cluster-info
      scale_down_replicas: 0
      scale_up_replicas: 2

    timeoutInMinutes: 5

    steps:
    - task: KubernetesManifest@0
      displayName: Scale
      inputs:
        kubernetesServiceConnection: pupa2
        action: scale
        kind: deployment
        name: jmeter-slaves
        replicas: 5
        namespace: jubernetes2


