# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#https://dev.azure.com/gstarczewski/jmeter/_apis/build/builds?api-version=5.1

# This pipeline requires that after one time set up of build agent correct kubernetes credentials are copied over to agent
#so that cluster can be accessed with kubectl remotely

name: $(BuildID)
trigger:
  - master
jobs:
  - job: Run_Jmeter_Tests
    pool: private
    variables:
      cluster_namespace: jmeter
      scenario: cloudssky.jmx
    timeoutInMinutes: 10

    steps:

      - task: ShellScript@2
        inputs:
          scriptPath: start_test_from_script_params.sh
          args: $(cluster_namespace) $(scenario)
        displayName: 'Run dummy test'

      - task: CmdLine@2
        displayName: List JMeter ReportDir
        inputs:
          script: 'ls -alh $(System.DefaultWorkingDirectory)/report'

      - task: PublishPipelineArtifact@1
        displayName: Archive JMeter Report
        inputs:
          path: $(System.DefaultWorkingDirectory)/report
          artifact: JmeterReport