# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#https://dev.azure.com/gstarczewski/jmeter/_apis/build/builds?api-version=5.1

# This pipeline requires that after one time set up of build agent correct kubernetes credentials are copied over to agent
#so that cluster can be accessed with kubectl remotely

name: $(BuildID)
trigger:
  - master
jobs:
  - job: Run_Jmeter_Tests
    pool: private
    variables:
      cluster_namespace: jmeter
      scenario: cloudssky.jmx
      scale_down_replicas: 0
      scale_up_replicas_slaves: 1
      scale_up_replicas_master: 1
      kubernetes_script_path: kubernetes/bin

    timeoutInMinutes: 10

    steps:
      - script: |
          kubectl scale deployment jmeter-master --replicas=$(scale_down_replicas) -n $(cluster_namespace)
        displayName: 'Scale down master to $(scale_down_replicas)'

      - script: |
          kubectl scale deployment jmeter-master --replicas=$(scale_up_replicas_master) -n $(cluster_namespace)
        displayName: 'Scale up master to $(scale_up_replicas_master)'

      - script: |
          kubectl scale deployment jmeter-slaves --replicas=$(scale_down_replicas) -n $(cluster_namespace)
        displayName: 'Scale down slaves to $(scale_down_replicas)'

      - script: |
          kubectl scale deployment jmeter-slaves --replicas=$(scale_up_replicas_slaves) -n $(cluster_namespace)
        displayName: 'Scale up slaves to $(scale_up_replicas_slaves)'

      - task: ShellScript@2
        displayName: Wait until service jmeter-master rescales
        inputs:
          scriptPath: $(kubernetes_script_path)/wait_for_service_to_scale.sh
          args: $(cluster_namespace) jmeter-master 1 5

      - task: ShellScript@2
        displayName: Wait until service jmeter-slaves rescales
        inputs:
          scriptPath: $(kubernetes_script_path)/wait_for_service_to_scale.sh
          args: $(cluster_namespace) jmeter-slaves 1 5

      - task: ShellScript@2
        inputs:
          scriptPath: $(kubernetes_script_path)/start_test_from_script_params.sh
          args: $(cluster_namespace) $(scenario)
        displayName: 'Run dummy test'

      - task: CmdLine@2
        displayName: List JMeter ReportDir
        inputs:
          script: 'ls -alh $(System.DefaultWorkingDirectory)/report'

      - task: PublishPipelineArtifact@1
        displayName: Archive JMeter Report
        inputs:
          path: $(System.DefaultWorkingDirectory)/report
          artifact: JmeterReport