# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#https://dev.azure.com/gstarczewski/jmeter/_apis/build/builds?api-version=5.1
name: $(BuildID)
trigger:
  - master

jobs:
  - job: jmeter_pipeline_maven
    pool: private
    variables:
      report_dir:  $(System.DefaultWorkingDirectory)/jmeter/as_maven/target/jmeter/reports
      jmeter_scenario_pom: 'jmeter/as_maven/pom.xml'
      jmeter_jvm_options: '-Xmx3072m'
      jmeter_scenario_name: 'cloudssky'


    timeoutInMinutes: 5

    steps:

      - task: Maven@3
        displayName: Run $(jmeter_scenario_name) with maven
        inputs:
          mavenPomFile: $(jmeter_scenario_pom)
          mavenOptions: $(jmeter_jvm_options)
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'verify'

      - task: PublishPipelineArtifact@1
        displayName: Archive Report for $(jmeter_scenario_name)
        inputs:
          path: $(report_dir)
          artifact: JmeterReport