# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#https://dev.azure.com/gstarczewski/jmeter/_apis/build/builds?api-version=5.1

# This pipeline requires that after one time set up of build agent correct kubernetes credentials are copied over to agent
#so that cluster can be accessed with kubectl remotely

name: $(BuildID)
trigger:
  - master
jobs:
  - job: Run_Jmeter_Tests
    pool: private
    variables:
      cluster_namespace: jmeter
      scenario: cloudssky.jmx
      scale_down_replicas: 0
      scale_up_replicas_slaves: 1
      scale_up_replicas_master: 1
      kubernetes_script_path: kubernetes/bin
      kubernetes_jmeter_master_service: jmeter-master
      kubernetes_jmeter_slave_service: jmeter-slaves
      report_dir: $(System.DefaultWorkingDirectory)/kubernetes/tmp/report
      artifact_name: jmeter_report
      base_url: http://10.1.137.108:8081
      repo: jmeter-artifacts
      project: cloudssky
      tribe: testing

    timeoutInMinutes: 10

    steps:
      - script: |
          kubectl scale deployment $(kubernetes_jmeter_master_service) --replicas=$(scale_down_replicas) -n $(cluster_namespace)
          kubectl scale deployment $(kubernetes_jmeter_master_service) --replicas=$(scale_up_replicas_master) -n $(cluster_namespace)
          kubectl scale deployment $(kubernetes_jmeter_slave_service) --replicas=$(scale_down_replicas) -n $(cluster_namespace)
          kubectl scale deployment $(kubernetes_jmeter_slave_service) --replicas=$(scale_up_replicas_slaves) -n $(cluster_namespace)
        displayName: 'Reset cluster'

      - task: ShellScript@2
        inputs:
          scriptPath: $(kubernetes_script_path)/wait_for_service_to_scale.sh
          args: $(cluster_namespace) jmeter-master 1 5
        displayName: 'Wait until service jmeter-master rescales'

      - task: ShellScript@2
        inputs:
          scriptPath: $(kubernetes_script_path)/wait_for_service_to_scale.sh
          args: $(cluster_namespace) jmeter-slaves 1 5
        displayName: 'Wait until service jmeter-slaves rescales'

      - task: ShellScript@2
        inputs:
          scriptPath: $(kubernetes_script_path)/start_test_from_script_params.sh
          args: $(cluster_namespace) $(scenario) -Gloops=10
        displayName: 'Run test $(scenario)'

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(report_dir)
          artifact: $(artifact_name)
        displayName: 'Archive JMeter Report'

      - task: ShellScript@2
        inputs:
          scriptPath: $(kubernetes_script_path)/upload_to_artifactory.sh
          args: $(artifact_name).zip $(report_dir) $(base_url) $(repo) $(tribe)/$(project) $(secret_artifactory_token)
        displayName: 'Artifactory upload'